# Generated by Django 5.2.4 on 2025-07-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nom_utilisateur',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
