# Generated by Django 5.2.4 on 2025-07-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_coaching_type_delete_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coaching_type',
            field=models.CharField(choices=[('life', 'Coaching de vie'), ('career', 'Coaching de carrière'), ('health', 'Coaching santé')], max_length=20),
        ),
    ]
