# Generated by Django 5.2.4 on 2025-07-14 08:55

import pyuploadcare.dj.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
    ]
