# Generated by Django 5.2.4 on 2025-07-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversationvoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConversationVoice',
        ),
    ]
